{% raw %}
# This is a workflow to run unit tests and report code coverage
name: Code Coverage - Java
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [synchronize, opened, reopened, edited]


jobs: 
  code-coverage:
    name: Run Tests and Generate Code Coverage - Java
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write    
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Run unit tests and generate code coverage report
      - name: Run Tests and Generate Code Coverage
        run: |
          mvn test \
      
      # Autocommit the files to PR (if any)
      - name: Checkout PR
        if: steps.tests.outcome == 'success' && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
    
      - name: Push changes
        if: steps.tests.outcome == 'success' && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "208695+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Bot [bot]" 
          git add target/site/jacoco/*.xml || true
          git commit -m "chore: save coverage report" || true
          git push || true

      # Publish unit test results
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Unit Test Results
          junit_files: "target/surefire-reports/*.xml"      
{% endraw %}