# https://github.com/telus/reference-architecture/blob/master/development/dependencies.md

version: 2
updates:
  #  npm packages
  - package-ecosystem: "npm"
    directory: "/app" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
