steps:
  - name: "node:${_NODE_VERSION}"
    entrypoint: "yarn"
    args: ["install"]
    dir: "."
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy event-driven Trigger function
    args:
      - gcloud
      - functions
      - deploy
      - ${_FUNCTION_TITLE}
      - --source=${_SOURCE}
      - --runtime=${_RUNTIME}
      - --trigger-topic=${_CQRS_TOPIC}
      - --region=${_REGION}
      - --entry-point=${_FUNCTION_NAME}
      - --set-env-vars=GCP_PROJECT=${_PROJECT_ID},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION},CQRS_TOPIC=${_CQRS_TOPIC}
      - --ingress-settings=internal-only

substitutions:
  _NODE_VERSION: "20"
  _FUNCTION_TITLE: CQRS-PubSub-Trgger-CloudFunction-Nodejs
  _FUNCTION_NAME: cqrsPubSub
  _SOURCE: .
  _RUNTIME: nodejs20
  _REGION: northamerica-northeast1
  _FIRESTORE_COLLECTION: {{ cookiecutter.cqrsPubsubTriggerCf.firestoreCollection }}
  _CQRS_TOPIC: {{ cookiecutter.cqrsPubsubTriggerCf.cqrsTopic }}
  _PROJECT_ID: {{ cookiecutter.cqrsPubsubTriggerCf.projectId }}
