steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy Java EDA function
    args:
      - gcloud
      - functions
      - deploy
      - ${_FUNCTION_TITLE}
      - --source=${_SOURCE}
      - --no-gen2
      - --runtime=${_RUNTIME}
      - --trigger-event=providers/cloud.firestore/eventTypes/document.create
      - --trigger-resource=projects/${PROJECT_ID}/databases/(default)/documents/${_FIRESTORE_COLLECTION}/{documentId}
      - --region=${_REGION}
      - --entry-point=${_FUNCTION_NAME}
      - --set-env-vars=GCP_PROJECT=${PROJECT_ID},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION},EDA_TOPIC=${_EDA_TOPIC}
      - --ingress-settings=internal-only


substitutions:
  # Name of the function that will show up in the GCP console
  _FUNCTION_TITLE: EDA-Firestore-Trigger-CF

  # Fully qualified name of the function class containing the entry point
  _FUNCTION_NAME: com.samples.telus.FirestoreBackgroundFunction

  # Points to the directory containing the pom.xml file
  _SOURCE: .

  # Runtime language and version
  _RUNTIME: java17

  # Region where the function will be deployed
  _REGION: northamerica-northeast1

  # Environment variables passed to the function
  _FIRESTORE_COLLECTION: {{cookiecutter.edaFsTriggerCf.firestoreCollection}}
  _EDA_TOPIC: {{cookiecutter.edaFsTriggerCf.edaTopic}}
