automatedReleaseApproved: false
groupConfigProfile: CIO
riskThreshold: 65

useGithubEvents: true
ignoredFiles:
  - "package-lock.json"
  - "notes/**"
  # Add additional file or folder paths that should be ignored from Risk Engine analysis i.e. generated files with no inherent risk
  # e.g. Add a pattern to match mocked files used in testing: - "**/mocks/**"
riskInputs:
  - name: prDescription
    prTemplatePath: ".github/pull_request_template.md"
  - name: testCoverage
    covReportPath: "app/.tap/coverage-summary.json"
    coverageReportType: "jsonSummary"
  - name: changedFiles
    matchChangesGlobPatterns:
      '**/*.md': low
      '**/*.js': medium
      routes/**: high
      config/**: critical
  - name: maintenanceWindow
    maintenanceDays:
      - day: Monday
        start: '01:00'
        end: '23:00'
      - day: Tuesday
        start: '01:00'
        end: '23:00'
      - day: Wednesday
        start: '01:00'
        end: '23:00'
      - day: Thursday
        start: '01:00'
        end: '23:00'
      - day: Friday
        start: '01:00'
        end: '23:00'
    deploymentBranch: main
  - name: dynatraceVulnerabilityAlerts
    # if your project has been configured for Dynatrace, set exempt to false.
    exempt: true
  - name: gkeTemplateHealth
    # When deploying your component to GKE, set alwaysEvaluate to true and enter the name of the gke configuration file for the deployment.
    alwaysEvaluate: false
    templatePath: "cicd/deployment/helm/<env-specific-heml-file.yaml>"
  