# service_map.sh

# Define card values
api_java="api-java"
etl_java="etl-java"
dlp_java="dlp-java"
eda_java="eda-java"
cqrs_java="cqrs-java"

api_js="api-js"
etl_js="etl-js"
dlp_js="dlp-js"
eda_js="eda-js"
cqrs_js="cqrs-js"

api_ts="api-ts"
etl_ts="etl-ts"
dlp_ts="dlp-ts"

api_js_fastify="api-js-fastify"
api_ts_fastify="api-ts-fastify"

etl_python="etl-python"

nextjs="nextjs"

# Define service mappings
declare -A card_map=(
  ["java:basic"]="$api_java"
  ["java:gcstorage"]="$api_java"
  ["java:secretmgr"]="$api_java"
  ["java:postgresql"]="$api_java"
  ["java:pubsub"]="$api_java"
  ["java:firestore"]="$api_java"
  ["java:memstore"]="$api_java"
  ["java:apiClient"]="$api_java"
  ["java:gqlPsql"]="$api_java"
  ["java:primavera"]="$api_java"
  ["java:unleashClient"]="$api_java"
  ["java:etlStorageCf"]="$etl_java"
  ["java:dlpStorageCf"]="$dlp_java"
  ["java:edaPublisher"]="$eda_java"
  ["java:edaSubscriber"]="$eda_java"
  ["java:edaFsTriggerCf"]="$eda_java"
  ["java:cqrsCmd"]="$cqrs_java"
  ["java:cqrsPubsubTriggerCf"]="$cqrs_java"
  ["java:cqrsQuery"]="$cqrs_java"

  ["nodejsExpress:basic"]="$api_js"
  ["nodejsExpress:gcstorage"]="$api_js"
  ["nodejsExpress:secretmgr"]="$api_js"
  ["nodejsExpress:postgresql"]="$api_js"
  ["nodejsExpress:pubsub"]="$api_js"
  ["nodejsExpress:firestore"]="$api_js"
  ["nodejsExpress:memstore"]="$api_js"
  ["nodejsExpress:apiClient"]="$api_js"
  ["nodejsExpress:gqlPsql"]="$api_js"
  ["nodejsExpress:primavera"]="$api_js"
  ["nodejsExpress:unleashClient"]="$api_js"
  ["nodejsExpress:etlStorageCf"]="$etl_js"
  ["nodejsExpress:dlpStorageCf"]="$dlp_js"
  ["nodejsExpress:edaPublisher"]="$eda_js"
  ["nodejsExpress:edaSubscriber"]="$eda_js"
  ["nodejsExpress:edaFsTriggerCf"]="$eda_js"
  ["nodejsExpress:cqrsCmd"]="$cqrs_js"
  ["nodejsExpress:cqrsPubsubTriggerCf"]="$cqrs_js"
  ["nodejsExpress:cqrsQuery"]="$cqrs_js"

  ["nodetsExpress:basic"]="$api_ts"
  ["nodetsExpress:secretmgr"]="$api_ts"
  ["nodetsExpress:gcstorage"]="$api_ts"
  ["nodetsExpress:firestore"]="$api_ts"
  ["nodetsExpress:postgresql"]="$api_ts"
  ["nodetsExpress:gqlPsql"]="$api_ts"
  ["nodetsExpress:pubsub"]="$api_ts"
  ["nodetsExpress:memstore"]="$api_ts"
  ["nodetsExpress:apiClient"]="$api_ts"
  ["nodetsExpress:primavera"]="$api_ts"
  ["nodetsExpress:etlStorageCf"]="$etl_ts"
  ["nodetsExpress:dlpStorageCf"]="$dlp_ts"

  ["nodejsFastify:basic"]="$api_js_fastify"
  ["nodejsFastify:gcstorage"]="$api_js_fastify"
  ["nodejsFastify:secretmgr"]="$api_js_fastify"
  ["nodejsFastify:firestore"]="$api_js_fastify"
  ["nodejsFastify:memstore"]="$api_js_fastify"
  ["nodejsFastify:pubsub"]="$api_js_fastify"
  ["nodejsFastify:unleashClient"]="$api_js_fastify"

  ["nodetsFastify:basic"]="$api_ts_fastify"
  ["nodetsFastify:secretmgr"]="$api_ts_fastify"

  ["python:etlStorageCf"]="$etl_python"

  ["nextjs:singlePage"]="$nextjs"
  ["nextjs:multiPage"]="$nextjs"
  ["nextjs:singlePageAPI"]="$nextjs"
  ["nextjs:multiPageAPI"]="$nextjs"
)
