# https://github.com/telus/reference-architecture/blob/master/development/dependencies.md

version: 2
updates:
  # api-java pom packages
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"