steps:
  - name: "node:${_NODE_VERSION}"
    entrypoint: "yarn"
    args: ["install"]
    dir: "."
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy event-driven Trigger function
    args:
      - gcloud
      - functions
      - deploy
      - ${_FUNCTION_TITLE}
      - --source=${_SOURCE}
      - --runtime=${_RUNTIME}
      - --trigger-event=providers/cloud.firestore/eventTypes/document.create
      - --trigger-resource=projects/${PROJECT_ID}/databases/(default)/documents/${_FIRESTORE_COLLECTION}/{documentId}
      - --region=${_REGION}
      - --entry-point=${_FUNCTION_NAME}
      - --set-env-vars=GCP_PROJECT=${PROJECT_ID},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION},EDA_TOPIC=${_EDA_TOPIC}
      - --ingress-settings=internal-only

substitutions:
  _NODE_VERSION: "20"
  _FUNCTION_TITLE: EDA-Firestore-Trigger-cf
  _FUNCTION_NAME: edaFirestore
  _SOURCE: .
  _RUNTIME: nodejs20
  _REGION: northamerica-northeast1
  _FIRESTORE_COLLECTION: {{ cookiecutter.edaFsTriggerCf.firestoreCollection }}
  _EDA_TOPIC: {{ cookiecutter.edaFsTriggerCf.edaTopic }}
